    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the statsf_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define STATSF_CODE(ptr)                ((ptr)->code)
#define STATSF_ROW(ptr)                 ((ptr)->row)
#define STATSF_ROWS(ptr)                ((ptr)->rows)
#define STATSF_ROWS_AE(ptr,c)           ((ptr)->rows[c])
#define STATSF_COL(ptr)                 ((ptr)->col)
#define STATSF_COLS(ptr)                ((ptr)->cols)
#define STATSF_COLS_AE(ptr,c)           ((ptr)->cols[c])
#define STATSF_SUM(ptr)                 ((ptr)->sum)
#define STATSF_NUMS(ptr)                ((ptr)->nums)
#define STATSF_NUMS_AE(ptr,c)           ((ptr)->nums[c])
#define STATSF_NUM_COUNT(ptr)           ((ptr)->num_count)
#define STATSF_ARRAY_SIZE(ptr)          ((ptr)->array_size)
#define STATSF_PARTITIONS(ptr)          ((ptr)->partitions)
#define STATSF_SUM_X(ptr)               ((ptr)->sum_x)
#define STATSF_SUM_X_2(ptr)             ((ptr)->sum_x_2)
#define STATSF_ROW_SUMS(ptr)            ((ptr)->row_sums)
#define STATSF_ROW_SUMS_AE(ptr,c)       ((ptr)->row_sums[c])
#define STATSF_COL_SUMS(ptr)            ((ptr)->col_sums)
#define STATSF_COL_SUMS_AE(ptr,c)       ((ptr)->col_sums[c])
#define STATSF_EXPECTED_MEAN(ptr)       ((ptr)->expected_mean)
#define STATSF_SUM_Y(ptr)               ((ptr)->sum_y)
#define STATSF_SUM_Y_2(ptr)             ((ptr)->sum_y_2)
#define STATSF_SUM_X_Y(ptr)             ((ptr)->sum_x_y)
#define STATSF_TMP_FILE(ptr)            ((ptr)->tmp_file)
#define STATSF_TMP_FILE_AE(ptr,c)       ((ptr)->tmp_file[c])
