    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the statsf_list_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define STATSF_LIST_COUNT(ptr)          ((ptr)->count)
#define STATSF_LIST_FUNCTIONS(ptr)      ((ptr)->functions)
#define STATSF_LIST_FUNCTIONS_AE(ptr,c) ((ptr)->functions[c])
