/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <xtend/string.h>   // strlcpy() on Linux
#include "statsf.h"


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for code member in a statsf_t structure.
 *      Use this function to set code in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      code is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_code is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_code        The new value for code
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      statsf_code_t   new_code;
 *
 *      if ( statsf_set_code(&statsf, new_code) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_code(statsf_t *statsf_ptr, statsf_code_t new_code)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->code = new_code;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for row member in a statsf_t structure.
 *      Use this function to set row in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      row is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_row is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_row         The new value for row
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      unsigned        new_row;
 *
 *      if ( statsf_set_row(&statsf, new_row) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_row(statsf_t *statsf_ptr, unsigned new_row)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->row = new_row;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for col member in a statsf_t structure.
 *      Use this function to set col in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      col is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_col is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_col         The new value for col
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      unsigned        new_col;
 *
 *      if ( statsf_set_col(&statsf, new_col) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_col(statsf_t *statsf_ptr, unsigned new_col)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->col = new_col;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for sum member in a statsf_t structure.
 *      Use this function to set sum in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      sum is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_sum is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_sum         The new value for sum
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      double          new_sum;
 *
 *      if ( statsf_set_sum(&statsf, new_sum) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_sum(statsf_t *statsf_ptr, double new_sum)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->sum = new_sum;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for nums member in a statsf_t structure.
 *      Use this function to set nums in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      nums is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_nums is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_nums        The new value for nums
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      double *        new_nums;
 *
 *      if ( statsf_set_nums(&statsf, new_nums) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_nums(statsf_t *statsf_ptr, double * new_nums)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( new_nums == NULL )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->nums = new_nums;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for an array element of nums member in a statsf_t
 *      structure. Use this function to set an element of the array
 *      nums in a statsf_t variable from non-member functions.
 *
 *      Note that there is an equivalent macro STATSF_SET_NUMS_AE(), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_nums_element is guaranteed by other means.
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      c               Subscript to the nums array
 *      new_nums_element The new value for nums[c]
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      size_t          c;
 *      double *        new_nums_element;
 *
 *      if ( statsf_set_nums(&statsf, c, new_nums_element) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      STATSF_SET_NUMS_AE(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_nums_ae(statsf_t *statsf_ptr, size_t c, double  new_nums_element)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->nums[c] = new_nums_element;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for nums member in a statsf_t structure.
 *      Use this function to set nums in a statsf_t variable
 *      from non-member functions.  This function copies the array pointed to
 *      by new_nums to ->nums.
 *
 *      Note that there is an equivalent macro STATSF_SET_NUMS(), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_nums is guaranteed by other means.
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_nums        The new value for nums
 *      array_size      Size of the nums array.
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      double *        new_nums;
 *      size_t          array_size;
 *
 *      if ( statsf_set_nums(&statsf, new_nums, array_size) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      STATSF_SET_NUMS(3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_nums_cpy(statsf_t *statsf_ptr, double * new_nums, size_t array_size)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( new_nums == NULL )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	{
	    size_t  c;
	    
	    // FIXME: Assuming all elements should be copied
	    for (c = 0; c < array_size; ++c)
		statsf_ptr->nums[c] = new_nums[c];
	}
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for num_count member in a statsf_t structure.
 *      Use this function to set num_count in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      num_count is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_num_count is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_num_count   The new value for num_count
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      size_t          new_num_count;
 *
 *      if ( statsf_set_num_count(&statsf, new_num_count) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_num_count(statsf_t *statsf_ptr, size_t new_num_count)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->num_count = new_num_count;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for array_size member in a statsf_t structure.
 *      Use this function to set array_size in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      array_size is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_array_size is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_array_size  The new value for array_size
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      size_t          new_array_size;
 *
 *      if ( statsf_set_array_size(&statsf, new_array_size) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_array_size(statsf_t *statsf_ptr, size_t new_array_size)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->array_size = new_array_size;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for partitions member in a statsf_t structure.
 *      Use this function to set partitions in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      partitions is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_partitions is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_partitions  The new value for partitions
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      unsigned        new_partitions;
 *
 *      if ( statsf_set_partitions(&statsf, new_partitions) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_partitions(statsf_t *statsf_ptr, unsigned new_partitions)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->partitions = new_partitions;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for sum_x member in a statsf_t structure.
 *      Use this function to set sum_x in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      sum_x is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_sum_x is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_sum_x       The new value for sum_x
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      double          new_sum_x;
 *
 *      if ( statsf_set_sum_x(&statsf, new_sum_x) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_sum_x(statsf_t *statsf_ptr, double new_sum_x)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->sum_x = new_sum_x;
	return STATSF_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <basic-stats/statsf.h>
 *      -lxtend
 *
 *  Description:
 *      Mutator for sum_x_2 member in a statsf_t structure.
 *      Use this function to set sum_x_2 in a statsf_t variable
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      sum_x_2 is a pointer, data previously pointed to should
 *      generally be freed before calling this function to avoid memory
 *      leaks.
 *
 *      Note that there is an equivalent macro (), which performs
 *      this function with no data verification or function call overhead.
 *      Use the macro version to maximize performance where the validity
 *      of new_sum_x_2 is guaranteed by other means.
 *      
 *
 *  Arguments:
 *      statsf_ptr      Pointer to the structure to set
 *      new_sum_x_2     The new value for sum_x_2
 *
 *  Returns:
 *      STATSF_DATA_OK if the new value is acceptable and assigned
 *      STATSF_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      statsf_t        statsf;
 *      double          new_sum_x_2;
 *
 *      if ( statsf_set_sum_x_2(&statsf, new_sum_x_2) == STATSF_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2021-09-18  gen-get-set Auto-generated from statsf.h
 ***************************************************************************/

int     statsf_set_sum_x_2(statsf_t *statsf_ptr, double new_sum_x_2)

{
    /* FIXME: Replace this with a proper sanity check */
    if ( 0 )
	return STATSF_DATA_OUT_OF_RANGE;
    else
    {
	statsf_ptr->sum_x_2 = new_sum_x_2;
	return STATSF_DATA_OK;
    }
}
